-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260725120000_invite_replay_guard.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Issue #94 (P0) — an accepted project invite must stop being a replayable grant.
--
-- Before this migration, `accept_project_invite` (last defined in
-- 20260506120400_accept_project_invite_with_org.sql) guarded ONLY the
-- `project_invites` status write behind `v_already_accepted_by_current_user`.
-- Every other write ran on every call, so re-presenting an already-accepted
-- token re-executed:
--
--   * the `project_members` upsert, whose `on conflict do update` rewrites
--     role, ai_access, viewer_regime, credit_limit, finance_visibility and
--     internal_docs_visibility from the snapshot captured at invite time; and
--   * the `org_members` insert, which sits outside the guarded block entirely.
--
-- Two user-driven, silent consequences followed:
--
--   1. Revoked access was self-restorable. `removeWorkspaceProjectMember`
--      (rovno src/data/workspace-source.ts) issues a plain DELETE on
--      project_members, and nothing in this schema invalidated the invite that
--      created the row. Re-opening the original link re-INSERTed the
--      membership, and re-added the user to the org.
--   2. Demotion was self-reversible, because the upsert rewrites exactly the
--      columns an owner lowers.
--
-- Neither needed intent: rovno src/pages/invite/InviteAccept.tsx calls the RPC
-- from a mount effect with no confirmation step, so revisiting the URL from a
-- bookmark, history entry or the original email was enough.
--
-- The enumerated backstops all failed: RLS is bypassed (security definer),
-- `enforce_project_member_delegation` resolves the actor from
-- `app.member_delegate_actor`, which this RPC had just set to the project
-- OWNER, `project_invites` has no `expires_at` column anywhere in the tree,
-- and `enforce_project_member_limits` is a seat counter, not an authorization
-- guard.
--
-- ---------------------------------------------------------------------------
-- What this migration does, and what it deliberately does NOT do
-- ---------------------------------------------------------------------------
--
-- It changes exactly one function and adds no new database object.
--
--   (a) Every write moves inside `if not v_already_accepted_by_current_user`:
--       the `project_members` upsert, the delegate-actor set_config pair, the
--       invite status write and the org add. Replaying an already-accepted
--       token can therefore no longer resurrect a removed membership, undo a
--       demotion, or re-add the org.
--
--   (b) The already-accepted path additionally refuses when the membership it
--       is supposed to represent no longer exists. This is a read plus a
--       raise, never a write. Without it the replay would return success and
--       the client would route a removed user to a project dashboard that RLS
--       renders empty, and the "accepted implies still a member" invariant
--       would have no enforcement at all.
--
-- An earlier revision of this change also added an AFTER DELETE trigger on
-- project_members to set the consumed invite to 'revoked'. It was REMOVED, and
-- no status write from a member-deletion path should be reintroduced without
-- solving the following first.
--
-- Any `update public.project_invites` re-enters
-- `enforce_project_invite_delegation`, a BEFORE INSERT OR UPDATE authorization
-- trigger. Its EFFECTIVE definition is 20260326170500:4, which SUPERSEDES the
-- original at 20260324140000:339. The effective one DOES honour
-- `app.member_delegate_actor` (it reads `current_setting(...)` and falls back
-- to `auth.uid()`), so a delegate-actor override is not the missing piece.
--
-- The blocker is actor-INDEPENDENT. The trigger calls
-- `assert_project_participant_delegate_ok`, whose only definition
-- (20260324140000:170) rejects an owner-role snapshot outright:
--
--     if p_role = 'owner' then
--       raise exception 'Owner role cannot be assigned through invites or member grants';
--
-- That check is reached before any actor authority is consulted, so with an
-- invite snapshot carrying role='owner' the owner's own
-- `delete from public.project_members` aborted and the member became
-- UNREMOVABLE. No `set_config` can rescue it: the raise does not depend on who
-- the actor is. A future fix has to exempt a status-only bookkeeping write
-- from the delegation assert, not merely re-point the actor.
--
-- Known holes left open on purpose, tracked as separate issues rather than
-- widened into this P0 fix:
--
--   * A still-PENDING second invite for the same person on the same project
--     survives removal and restores membership through the first-acceptance
--     path. `idx_project_invites_active_email` is partial
--     (`where status = 'pending'`), so an accepted row and a pending row can
--     legally coexist.
--   * 'revoked' and 'expired' are not terminal. There is no status-transition
--     guard, and `project_invites_update` (20260306170000:334) is
--     `using (public.can_manage_project(project_id))` = owner OR co_owner, so
--     a status can be walked back to 'pending' and the original token
--     re-armed. `invite_token` is never rotated.
--   * Nothing server-side ever deletes `org_members`, so org membership (and
--     org-scoped visibility) outlives project membership. Whether it should is
--     an open product decision, NOT something this migration settles.
--   * No backfill. Invites already 'accepted' whose member row was deleted
--     before this migration keep status='accepted'. Point (b) makes them
--     inert, but the recorded state stays dishonest.
--
-- Idempotent: a single `create or replace function`, safe to re-apply, which
-- matters because prod applies with `supabase db push --include-all` and this
-- repo has out-of-band apply paths that can miss the schema_migrations ledger.

create or replace function public.accept_project_invite(p_invite_token text)
returns public.project_invites
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invite public.project_invites%rowtype;
  v_profile_email text;
  v_owner_profile_id uuid;
  v_already_accepted_by_current_user boolean := false;
  v_org_id uuid;
  v_inviter_in_org boolean;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select *
  into v_invite
  from public.project_invites
  where invite_token = p_invite_token
  for update;

  if not found then
    raise exception 'Invite not found';
  end if;

  if v_invite.status = 'accepted' and v_invite.accepted_profile_id = auth.uid() then
    v_already_accepted_by_current_user := true;
  elsif v_invite.status <> 'pending' then
    raise exception 'Invite is no longer pending';
  end if;

  select p.email
  into v_profile_email
  from public.profiles p
  where p.id = auth.uid();

  if not found then
    raise exception 'Profile not found';
  end if;

  if not v_already_accepted_by_current_user
     and (v_profile_email is null or lower(v_profile_email) <> lower(v_invite.email)) then
    raise exception 'Invite email does not match the current account';
  end if;

  -- An accepted invite is only ever a record of a membership that exists. Once
  -- that membership is COMMITTED-removed the token stops resolving, so the
  -- replay no longer reports success and the client no longer routes a removed
  -- user into a project they cannot read.
  --
  -- Scope of that guarantee, stated precisely: the `for update` above locks the
  -- INVITE row only, and nothing here locks project_members. Under READ
  -- COMMITTED a concurrent, still-uncommitted `delete from project_members` is
  -- invisible to this read and does not block it, so a replay racing a removal
  -- can still return success. That window writes NOTHING (no membership is
  -- resurrected, no status changes); the only consequence is a dashboard that
  -- RLS renders empty. Closing it would need `for key share` on the member row.
  --
  -- Placed before the owner lookup so that an ex-owner whose member row was
  -- removed after an ownership transfer gets this message instead of the
  -- misleading 'Owner invites are not supported...'. It is NOT about deleted
  -- projects: project_invites.project_id is ON DELETE CASCADE
  -- (20260306161000:42), so a deleted project takes its invites with it and the
  -- select above already reports 'Invite not found'.
  if v_already_accepted_by_current_user
     and not exists (
       select 1
       from public.project_members pm
       where pm.project_id = v_invite.project_id
         and pm.profile_id = auth.uid()
     ) then
    raise exception 'Project access for this invite was withdrawn';
  end if;

  select p.owner_profile_id
  into v_owner_profile_id
  from public.projects p
  where p.id = v_invite.project_id;

  if not found then
    raise exception 'Project not found';
  end if;

  if v_invite.role = 'owner'
     and v_owner_profile_id is distinct from auth.uid() then
    raise exception 'Owner invites are not supported without a project ownership transfer';
  end if;

  -- Every write below is first-acceptance only. A replay of an already-accepted
  -- token reaches `return v_invite` without touching project_members,
  -- project_invites or org_members.
  if not v_already_accepted_by_current_user then
    -- Acceptance should honor a previously created invite even if inviter authority changed later.
    -- Delegate authority-trigger checks to project owner for acceptance flow.
    perform set_config('app.member_delegate_actor', v_owner_profile_id::text, true);

    begin
      insert into public.project_members (
        project_id,
        profile_id,
        role,
        ai_access,
        viewer_regime,
        credit_limit,
        used_credits,
        finance_visibility,
        internal_docs_visibility
      )
      values (
        v_invite.project_id,
        auth.uid(),
        v_invite.role,
        v_invite.ai_access,
        v_invite.viewer_regime,
        v_invite.credit_limit,
        0,
        v_invite.finance_visibility,
        v_invite.internal_docs_visibility
      )
      on conflict (project_id, profile_id) do update
        set role = excluded.role,
            ai_access = excluded.ai_access,
            viewer_regime = excluded.viewer_regime,
            credit_limit = excluded.credit_limit,
            finance_visibility = excluded.finance_visibility,
            internal_docs_visibility = excluded.internal_docs_visibility;

      update public.project_invites
      set status = 'accepted',
          accepted_profile_id = auth.uid(),
          accepted_at = coalesce(accepted_at, now())
      where id = v_invite.id
      returning * into v_invite;
    exception
      when others then
        perform set_config('app.member_delegate_actor', '', true);
        raise;
    end;

    perform set_config('app.member_delegate_actor', '', true);

    -- Optional org membership add. Validates that the inviter is still a
    -- member of the target org before adding the acceptee. If the inviter has
    -- left the org by acceptance time, we silently skip the org add — the
    -- project membership remains valid (graceful degradation).
    v_org_id := v_invite.add_to_org_id;
    if v_org_id is not null then
      select exists (
        select 1
        from public.organizations o
        where o.id = v_org_id and o.owner_profile_id = v_invite.invited_by
      ) or exists (
        select 1
        from public.org_members om
        where om.org_id = v_org_id and om.profile_id = v_invite.invited_by
      )
      into v_inviter_in_org;

      if v_inviter_in_org then
        insert into public.org_members (org_id, profile_id, role)
        values (v_org_id, auth.uid(), 'member')
        on conflict (org_id, profile_id) do nothing;
      end if;
    end if;
  end if;

  return v_invite;
end;
$$;
